# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525a01ededc37f3d176a8070a3213e5c94eca0dc733f4151b74fcdbb367152c7a618cb565320d5bde2f626403203f25b64c78579fd84a84fa36f7520067a2750

test:
  secret_key_base: b518a645d547d23054dd6e5bd9318fa0e75db5f648d8cc19c40dedc8fb648db99d05cf743c09a28df0b0418d9cc83222b014eab7b344e0b27ba3dbca0e5d5507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
